### ISSUE TITLE
想下载历史数据怎么做呢

### ISSUE THREAD

**Issue by yyz944600382** [zhu6201976/aqistudy20220801#2]

**Comment by zhu6201976** [comment]
这个请自行研究探索吧，网站接口众多，暂无精力逆向所有，而且公开也不太合适，项目研究性质。

**Comment by yyz944600382** [comment]
谢谢你





------------------ 原始邮件 ------------------
发件人: 雄霸天下 ***@***.***&gt;
发送时间: 2022年10月29日 16:12
收件人: zhu6201976/aqistudy20220801 ***@***.***&gt;
抄送: yyz944600382 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zhu6201976/aqistudy20220801] 想下载历史数据怎么做呢 (Issue #2)





 
这个请自行研究探索吧，网站接口众多，暂无精力逆向所有，而且公开也不太合适，项目研究性质。
